"""update animais table

Revision ID: d7ac022fad9a
Revises: 2de6922737ac
Create Date: 2025-05-20 12:51:01.096144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7ac022fad9a'
down_revision: Union[str, None] = '2de6922737ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animais', 'baia',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('animais', 'lote',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('animais', 'idade_mes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('animais', 'sexo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('animais', 'raca',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('animais', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('animais', 'peso_balancinha',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('animais', 'peso_saida',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('animais', 'proprietario',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('animais', 'cod_pelagem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animais', sa.Column('cod_pelagem', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('animais', 'proprietario',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('animais', 'peso_saida',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('animais', 'peso_balancinha',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('animais', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('animais', 'raca',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('animais', 'sexo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('animais', 'idade_mes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('animais', 'lote',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('animais', 'baia',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_table('log_insercao_animais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('docentry', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('mensagem', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_log', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='log_insercao_animais_pkey')
    )
    # ### end Alembic commands ###
